defaults: &defaults
  adapter: mysql2
  encoding: utf8
  database: sass_test
  host: localhost
  username: ''
  password: ''
  pool: 15

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
